#server
server:
  port: 8090
  tomcat.uri-encoding: UTF-8
  servlet:
    context-path: /grade
    session:
      timeout: 60m
#spring.datasource
spring:
#  security:
#    user:
#      name: chad
#      password: 123456
  datasource:
    url: jdbc:mysql://localhost:3306/student_manage?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC
    username: root
    password: mysql
    sql-script-encoding: utf-8
    #thymeleaf start
    dbcp2:
      max-idle: 10
      min-idle: 5
      initial-size: 5
      max-wait-millis: 10000
  thymeleaf:
    mode: HTML5
    encoding: UTF-8
    prefix: classpath:/templates/
    suffix: .html
    #开发时关闭缓存,不然没法看到实时页面
    cache: false
    #thymeleaf end
    servlet:
      content-type: text/html
  jmx:
    enabled: false
  devtools:
    restart:
      enabled: true
  jackson:
    serialization:
      write-dates-as-timestamps: true
  servlet:
    multipart:
      max-file-size: 5242880
      max-request-size: 5242880
#mybatis.config= classpath:mybatis-config.xml
mybatis:
  mapper-locations: classpath:mappers/*.xml
  typeAliasesPackage: com.school.grade.entity
  config-location: classpath:mybatis/mybatis-config.xml

